name: Run tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests-macos:
    name: Run tests (macOS)
    runs-on: macos-15
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history and tags

      - name: Select Xcode
        uses: ./.github/actions/select-xcode

      - name: Delete build artifacts
        run: swift package clean

      - name: Run package tests
        run: swift test --enable-code-coverage

      - name: Generate LCOV report
        run: |
          BIN_PATH="$(swift build --show-bin-path)"
          XCTEST_PATH="$(find "${BIN_PATH}" -name '*.xctest' | head -1)"
          f="$(basename "${XCTEST_PATH}" .xctest)"
          xcrun llvm-cov export \
            "${XCTEST_PATH}/Contents/MacOS/${f}" \
            -instr-profile=".build/debug/codecov/default.profdata" \
            -format="lcov" \
            -ignore-filename-regex=".build|Tests" \
            > coverage.lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.lcov
          flags: macos
          fail_ci_if_error: true

  run-tests-linux:
    name: Run tests (Linux)
    runs-on: ubuntu-latest
    container: swift:6.0-jammy
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Delete build artifacts
        run: swift package clean

      - name: Run package tests
        run: swift test --enable-code-coverage

      - name: Generate LCOV report
        run: |
          BIN_PATH="$(swift build --show-bin-path)"
          XCTEST_PATH="$(find "${BIN_PATH}" -name '*.xctest' | head -1)"
          llvm-cov export \
            "${XCTEST_PATH}" \
            -instr-profile=".build/debug/codecov/default.profdata" \
            -format="lcov" \
            -ignore-filename-regex=".build|Tests" \
            > coverage.lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.lcov
          flags: linux
          fail_ci_if_error: true
